openapi: 3.0.0
info:
  title: EV Dealer Backend API
  version: 1.0.0
  description: API documentation for EV Dealer Management System

servers:
  - url: http://localhost:3000/api
    description: Local server

tags:
  - name: Auth
    description: Authentication APIs (Register & Login)

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: huytran
                email:
                  type: string
                  example: huy@example.com
                password:
                  type: string
                  example: 123456
                role:
                  type: string
                  enum: [dealer_staff, dealer_manager, evm_staff, admin]
                  example: dealer_staff
              required: [username, email, password, role]
      responses:
        200:
          description: User created successfully
        400:
          description: Validation errors
        500:
          description: Server error

  /auth/login:
    post:
      summary: Login to the system
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: huy@example.com
                password:
                  type: string
                  example: 123456
              required: [email, password]
      responses:
        200:
          description: Login successful
        400:
          description: Validation errors
        401:
          description: Invalid credentials
        500:
          description: Server error
