openapi: 3.0.0
info:
  title: EV Dealer Backend API
  version: 1.0.0
  description: API documentation for EV Dealer Management System

servers:
  - url: http://localhost:3000/api
    description: Local server

tags:
  - name: Auth
    description: Authentication APIs (Register & Login)

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: huytran
                email:
                  type: string
                  example: huy@example.com
                password:
                  type: string
                  example: 123456
                role:
                  type: string
                  enum: [dealer_staff, dealer_manager, evm_staff, admin]
                  example: dealer_staff
              required: [username, email, password, role]
      responses:
        200:
          description: User created successfully
        400:
          description: Validation errors
        500:
          description: Server error

  /auth/login:
    post:
      summary: Login to the system
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: huy@example.com
                password:
                  type: string
                  example: 123456
              required: [email, password]
      responses:
        200:
          description: Login successful
        400:
          description: Validation errors
        401:
          description: Invalid credentials
        500:
          description: Server error

  /auth/customers/google:
    post:
      summary: Login/Register with Google
      tags: [Auth]
      description: Đăng nhập hoặc đăng ký Customer bằng tài khoản Google
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idToken:
                  type: string
                  description: Google ID Token từ frontend
                  example: eyJhbGciOiJSUzI1NiIsImtpZCI6IjE3ZjBmMGYxNGU5...
              required: [idToken]
      responses:
        200:
          description: Login thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Google login thành công
                  customer:
                    type: object
                    properties:
                      id:
                        type: string
                        example: b6f3c891-3d45-4cc7-823f-01bce4f7bfe8
                      email:
                        type: string
                        example: test@gmail.com
                      full_name:
                        type: string
                        example: Swagger User
                  token:
                    type: string
                    description: JWT nội bộ trả về
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        400:
          description: Thiếu token hoặc token không hợp lệ
        500:
          description: Lỗi xác thực Google
